import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import '../config.dart';
import 'options_dev.dart' as dev;
import 'options_prod.dart' as prod;

/// Starts Firebase for this build's environment — the live project
/// (spiritpedia) for APP_ENV=prod, spiritpedia-dev otherwise — the same way
/// the build already picks its Supabase project. Both Firebase projects
/// register the same bundle ID and package name, so one app binary serves
/// either; the options files are generated by `flutterfire configure`.
///
/// Only Cloud Messaging is used. Starting Firebase does not create a
/// notification token: auto-init is off until the person says yes.
///
/// Returns false (push unavailable) rather than throwing, so a build without
/// Firebase config still runs.
Future<bool> initFirebase() async {
  try {
    await Firebase.initializeApp(
      options: AppConfig.isProduction
          ? prod.DefaultFirebaseOptions.currentPlatform
          : dev.DefaultFirebaseOptions.currentPlatform,
    );
    return true;
  } catch (e) {
    debugPrint('Firebase unavailable: $e');
    return false;
  }
}
